version: '3'

networks:
  sql_net:
    driver: bridge

services:

  postgres:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - sql_net

  db_loader:
    image: db_loader_net:latest
    build: ./
    restart: always
    ports:
      - "5000:5000"
    depends_on:
     - postgres
    networks:
      - sql_net

volumes:
  db:
    driver: local
      



