version: '3'

networks:
  mysql:
    driver: bridge

services:

  mysql:
    image: mysql:8.0.27
    volumes:
      - "./.mysql-data/db:/var/lib/mysql"
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: sys
    networks:
      - mysql

  postgres:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - mysql

  db_loader:
    image: db_loader_net:latest
    build: ./
    restart: always
    ports:
      - "5000:5000"
    depends_on:
     - mysql
    networks:
      - mysql

volumes:
  db:
    driver: local
      



